# -*- coding: utf-8 -*-
"""SVM_Credit_Card_Fraud_Detection.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1SYDS9Wgto5DGLL1kQ51mRiv74sWhjot2
"""

!pip install -q kaggle

import pandas as pd
import numpy as np

from sklearn.model_selection import train_test_split
from sklearn.preprocessing import LabelEncoder, StandardScaler
from sklearn.svm import SVC
from sklearn.metrics import classification_report, confusion_matrix, accuracy_score

from google.colab import files
files.upload()

!mkdir -p ~/.kaggle
!cp kaggle.json ~/.kaggle/
!chmod 600 ~/.kaggle/kaggle.json

!kaggle competitions download -c ieee-fraud-detection

!unzip ieee-fraud-detection.zip

train_trans = pd.read_csv("train_transaction.csv")
train_id = pd.read_csv("train_identity.csv")

# Merge on TransactionID
train_data = train_trans.merge(train_id, on="TransactionID", how="left")

print(train_data.shape)
train_data.head()

# Sample 10,000 rows for safe SVM training
train_sample = train_data.sample(n=10000, random_state=42)

print(train_sample['isFraud'].value_counts())

drop_cols = ['TransactionID', 'TransactionDT']
X = train_sample.drop(columns=['isFraud'] + drop_cols)
y = train_sample['isFraud']

categorical_cols = X.select_dtypes(include='object').columns

for col in categorical_cols:
    le = LabelEncoder()
    X[col] = X[col].fillna("NA")
    X[col] = le.fit_transform(X[col])

X = X.fillna(0)

X_train, X_test, y_train, y_test = train_test_split(
    X, y, test_size=0.2, random_state=42, stratify=y
)

scaler = StandardScaler()
X_train_scaled = scaler.fit_transform(X_train)
X_test_scaled = scaler.transform(X_test)

print(" Scaling completed")

svm_model = SVC(
    kernel='rbf',
    class_weight='balanced',
    probability=True
)

print("🚀 Training SVM...")
svm_model.fit(X_train_scaled, y_train)

print(" SVM training completed!")

y_pred = svm_model.predict(X_test_scaled)

print("Accuracy:", accuracy_score(y_test, y_pred))
print("\nClassification Report:\n")
print(classification_report(y_test, y_pred))

cm = confusion_matrix(y_test, y_pred)
cm

import joblib

joblib.dump(svm_model, "svm_fraud_model.pkl")
joblib.dump(scaler, "scaler.pkl")

print(" Model and scaler saved successfully")

from google.colab import files

files.download("svm_fraud_model.pkl")
files.download("scaler.pkl")